<?php

/**
 * @file
 * Contain all hook functions for Developer Demo module.
 */

/**
 * Implements hook_modules_install().
 *
 * Install fill visualization module fields with demo data.
 */
function developer_demo_modules_installed(array $modules, bool $is_syncing): void {
  if (in_array('developer_visualization', $modules)) {
    $creator_service = \Drupal::service('developer_demo.create_data');
    $creator_service->initVisualizationCreator();
  }
}
